account_file: account.json
login_qrcode: true
qrcode_path: qr.png
save_cookie: true
prefix: /
name_bot: bot tự code hơi lỏ
admin_bot:
  - "4977998388121318924"
  - "126026046603679910"
  - "8638694816918041595"
  - "1405311274332091801"
  - "4192574087260304182"
support_bot: null
allow_private_command: true
zca_js_config:
  selfListen: true
  checkUpdate: true
  logging: true
